name: native_splash_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.5
  speech_to_text: ^7.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7
  rename_app: ^1.6.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/flutter_icon.png

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/bun.jpg
  android: true
  ios: true
  web: true
  android_12:
    image: assets/images/bun.jpg
    color: "#42a5f5"
  android_gravity: fill
  ios_content_mode: scaleAspectFit
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/flutter_icon.png
    - assets/images/second_icon.png
    - assets/images/yello_icon.png
    - assets/images/story_bun.jpg
    - assets/images/bun.jpg
